name: ChatItemDisplay
main: me.bingorufus.chatitemdisplay.ChatItemDisplay
description: Display items in chat
api-version: 1.13
author: BingoRufus
version: ${project.version}
softdepend: [ProtocolLib,DiscordSRV]
load: POSTWORLD

commands:
  viewdisplay:
    description: See what item a player is displaying
    usage: /<command> <player/id>
    aliases: [viewitem,viewinv,viewinventory,viewec,viewenderchest,displayview]
  chatitemreload:
    usage: /<command>
    permission: chatitemdisplay.reload
    description: Reload the ChatItemDisplay config
  displayitem:
    usage: /<command>
    description: Display your items in chat
    aliases: [display]
  displayinventory:
    usage: /<command>
    description: Display your inventory
    aliases: [displayinv]
  displayenderchest:
    usage: /<command>
    description: Display your ender chest
    aliases: [displayec, displayendchest]
    
permissions:
  ChatItemDisplay.*:
    description: Parent node to all ChatItemDisplay permissions
    default: op
    children:
      ChatItemDisplay.reload:
        description: Reload the ChatItemDisplay config
        default: op
      ChatItemDisplay.display.*:
        description: Display Objects
        default: true
        children:
          chatitemdisplay.display.item:
            description: Display items
          chatitemdisplay.display.inventory:
            description: Display player inventories
          chatitemdisplay.display.enderchest:
            description: Display Ender Chests
            
      ChatItemDisplay.cooldownbypass:
        description: Bypass the display cooldown
        default: op
      ChatItemDisplay.blacklistbypass:
        description: Display blacklisted items
        default: op